import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { execa } from "execa"
import {
  juntoDir, readActiveId, readConfig, readTask, requiredPhases, setActiveId, taskDir, writeTask,
  SCHEMA_VERSION,
  type GateStatus, type Size, type Task,
} from "@junto/core"
import type { ToolContext } from "../context.js"

export type TaskToolInput =
  | { action: "start", title: string, size: Size, gates?: string[] }
  | { action: "switch", id: string }
  | { action: "finish" }

const MAX_SLUG = 40

// IDs generated by junto must match this shape. switchTo() also uses it to reject untrusted input.
const TASK_ID_PATTERN = /^\d{4}-\d{2}-\d{2}-[a-z0-9-]+$/

export function newTaskId(title: string, now: Date): string {
  const date = now.toISOString().slice(0, 10)
  const slug = title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u0111/g, "d").replace(/\u0110/g, "D")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_SLUG)
    .replace(/-+$/, "")
  // Fall back to "task" when normalization leaves no ASCII slug characters.
  return `${date}-${slug === "" ? "task" : slug}`
}

async function currentCommit(root: string): Promise<string | null> {
  try {
    const res = await execa("git", ["rev-parse", "HEAD"], { cwd: root, reject: false })
    return res.exitCode === 0 ? res.stdout.trim() : null
  } catch {
    return null
  }
}

async function start(ctx: ToolContext, input: Extract<TaskToolInput, { action: "start" }>): Promise<string> {
  if (readActiveId(ctx.root) !== null) {
    throw new Error(
      "A task is already active. junto supports one active task at a time; "
      + "run /junto:finish for the current task first.",
    )
  }

  const config = readConfig(ctx.root)
  const now = new Date()
  const id = newTaskId(input.title, now)
  const iso = now.toISOString()

  const dir = taskDir(ctx.root, id)
  const archiveDir = join(juntoDir(ctx.root), "archive", id)
  // Fail closed before creating files: check both active and archived destinations.
  if (existsSync(dir)) {
    throw new Error(
      `Task "${id}" already exists in .junto/tasks/ (same date and title as an open task). `
      + "Choose a different title to avoid an ID collision.",
    )
  }
  if (existsSync(archiveDir)) {
    throw new Error(
      `Task "${id}" already exists in .junto/archive/ (same date and title as an archived task). `
      + "Choose a different title to avoid an ID collision.",
    )
  }

  const gates: Record<string, GateStatus> = {}
  const names = input.gates ?? Object.keys(config.gates)
  for (const name of names) {
    const spec = config.gates[name]
    if (!spec) continue
    gates[name] = { required: spec.required, verdict: null, stale: false, failStreak: 0 }
  }

  // Read the initial phase from the single policy source in requiredPhases().
  const order = requiredPhases(input.size)
  const firstPhase = order[0]
  if (firstPhase === undefined) {
    throw new Error(`requiredPhases("${input.size}") returned no initial phase.`)
  }

  const task: Task = {
    schemaVersion: SCHEMA_VERSION,
    id,
    title: input.title,
    size: input.size,
    phase: firstPhase,
    baseCommit: await currentCommit(ctx.root),
    createdAt: iso,
    updatedAt: iso,
    phases: { [firstPhase]: { status: "active", at: iso } },
    gates,
    decisions: [],
    consults: [],
  }

  mkdirSync(join(dir, "verdicts"), { recursive: true })
  if (!existsSync(join(dir, "brief.md"))) writeFileSync(join(dir, "brief.md"), "", "utf-8")
  writeFileSync(join(dir, "context.jsonl"), "", "utf-8")
  writeTask(ctx.root, task)
  setActiveId(ctx.root, id)

  // junto owns .junto/.gitignore and never touches the project's root .gitignore.
  const ignore = join(juntoDir(ctx.root), ".gitignore")
  if (!existsSync(ignore)) writeFileSync(ignore, "*.log\n", "utf-8")

  return `Created task "${id}" (size ${input.size}) in phase ${firstPhase}. `
    + `Gates: ${Object.keys(gates).join(", ") || "none"}.`
}

function finish(ctx: ToolContext): string {
  const id = readActiveId(ctx.root)
  if (id === null) throw new Error("There is no active task to finish.")

  const task = readTask(ctx.root, id)
  if (task.phase !== "done") {
    throw new Error(
      `Task "${id}" is not in the done phase (current: "${task.phase}"). `
      + "Run /junto:verify and pass every required gate before finishing.",
    )
  }
  const from = taskDir(ctx.root, id)
  const to = join(juntoDir(ctx.root), "archive", id)

  // Safety net for an archive directory created manually between start and finish.
  if (existsSync(to)) {
    throw new Error(
      `Task "${id}" already exists in .junto/archive/. junto will not overwrite it; `
      + "inspect the archive directory before trying again.",
    )
  }

  mkdirSync(join(juntoDir(ctx.root), "archive"), { recursive: true })

  const gateLines = Object.entries(task.gates)
    .map(([n, g]) => `- ${n}: ${g.verdict === null ? "not run" : g.stale ? "stale" : "run"}${g.required ? " (required)" : ""}`)
    .join("\n")
  const summary = `# ${task.title}\n\n`
    + `- id: ${task.id}\n- size: ${task.size}\n- final phase: ${task.phase}\n`
    + `- created: ${task.createdAt}\n- finished: ${new Date().toISOString()}\n\n`
    + `## Gates\n\n${gateLines || "(none)"}\n\n`
    + `## Decisions\n\n${task.decisions.map(d => `- ${d.what} - ${d.why}`).join("\n") || "(none)"}\n`

  writeFileSync(join(from, "summary.md"), summary, "utf-8")
  renameSync(from, to)
  setActiveId(ctx.root, null)

  return `Archived task "${id}" at .junto/archive/${id}/.`
}

function switchTo(ctx: ToolContext, id: string): string {
  // The ID comes directly from an MCP call; validate it before using it in a path.
  if (!TASK_ID_PATTERN.test(id)) {
    throw new Error(`Invalid task ID "${id}". Expected YYYY-MM-DD-slug.`)
  }
  if (!existsSync(join(taskDir(ctx.root, id), "task.json"))) {
    throw new Error(`Task "${id}" was not found in .junto/tasks/.`)
  }
  setActiveId(ctx.root, id)
  const task = readTask(ctx.root, id)
  return `Switched to task "${id}" (phase ${task.phase}).`
}

export async function taskTool(ctx: ToolContext, input: TaskToolInput): Promise<string> {
  switch (input.action) {
    case "start": return start(ctx, input)
    case "finish": return finish(ctx)
    case "switch": return switchTo(ctx, input.id)
  }
}
